# Use Node.js official image as base
FROM node:22.12-alpine

# Set working directory
WORKDIR /app

# Verify Node.js version
RUN node --version && npm --version

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install --verbose

# Copy the rest of the application code
COPY . .

# Build the application for production
RUN npm run build-prod --verbose

# Run tests and generate coverage report
RUN npm run test:coverage